// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: feed/v1/api.proto

package feedv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on NextRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NextRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NextRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in NextRequestMultiError, or
// nil if none found.
func (m *NextRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *NextRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return NextRequestMultiError(errors)
	}
	return nil
}

// NextRequestMultiError is an error wrapping multiple validation errors
// returned by NextRequest.ValidateAll() if the designated constraints aren't met.
type NextRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NextRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NextRequestMultiError) AllErrors() []error { return m }

// NextRequestValidationError is the validation error returned by
// NextRequest.Validate if the designated constraints aren't met.
type NextRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NextRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NextRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NextRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NextRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NextRequestValidationError) ErrorName() string { return "NextRequestValidationError" }

// Error satisfies the builtin error interface
func (e NextRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNextRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NextRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NextRequestValidationError{}

// Validate checks the field values on NextResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NextResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NextResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in NextResponseMultiError, or
// nil if none found.
func (m *NextResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *NextResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPost()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, NextResponseValidationError{
					field:  "Post",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, NextResponseValidationError{
					field:  "Post",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPost()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return NextResponseValidationError{
				field:  "Post",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return NextResponseMultiError(errors)
	}
	return nil
}

// NextResponseMultiError is an error wrapping multiple validation errors
// returned by NextResponse.ValidateAll() if the designated constraints aren't met.
type NextResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NextResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NextResponseMultiError) AllErrors() []error { return m }

// NextResponseValidationError is the validation error returned by
// NextResponse.Validate if the designated constraints aren't met.
type NextResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NextResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NextResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NextResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NextResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NextResponseValidationError) ErrorName() string { return "NextResponseValidationError" }

// Error satisfies the builtin error interface
func (e NextResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNextResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NextResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NextResponseValidationError{}
